export const translations = {
  id: {
    headerTitle: "BARANTIN DSS",
    headerSubtitle: "Badan Karantina Indonesia - Deteksi OPTK",
    analysisFailed: "Analisis Gagal",
    tryAgain: "Coba Lagi",
    fixConnection: "Perbaiki Koneksi",
    uploadSample: "Upload Sampel",
    clickToChange: "Klik untuk mengganti gambar",
    dragDrop: "Pilih atau Tarik Gambar",
    formatInfo: "Format JPG, PNG (Max 5MB)",
    analyzeBtn: "Analisis dengan AI",
    analyzingBtn: "Menganalisis...",
    integratedSystem: "Sistem Terintegrasi",
    analyzingTitle: "Sedang Menganalisis",
    analyzingDesc: "AI sedang memproses gambar Anda. Proses ini dioptimalkan untuk selesai dalam waktu kurang dari 30 detik.",
    processStatus: "Status Proses",
    active: "Aktif",
    quarantineTips: "Tips Karantina",
    quarantineTipText: "\"Pastikan gambar sampel memiliki pencahayaan yang cukup dan fokus pada bagian tubuh serangga yang khas (sayap, antena, atau tungkai) untuk hasil identifikasi yang lebih akurat.\"",
    confidence: "Kepercayaan",
    risk: "RISIKO",
    taxonomy: "Taksonomi",
    taxonomyHierarchy: "Hierarki Taksonomi (Scientific Lineage)",
    kingdom: "Kingdom",
    phylum: "Filum",
    class: "Kelas",
    order: "Ordo",
    family: "Famili",
    genus: "Genus",
    species: "Spesies",
    target: "Target",
    riskAnalysis: "Analisis Risiko",
    riskDetails: "Detail Risiko & Dampak",
    potentialDamage: "Potensi Kerusakan",
    spreadRate: "Laju Penyebaran",
    economicImpact: "Dampak Ekonomi",
    scientificReasoning: "Alasan Ilmiah",
    scopusLiterature: "LITERATUR TERINDEKS SCOPUS",
    mitigationTitle: "Rekomendasi Mitigasi & Perlakuan",
    mitigation: "Rekomendasi Mitigasi & Perlakuan",
    farmerLevel: "Tingkat Petani",
    domesticMitigation: "Domestik / Antar Area",
    domestic: "Domestik / Antar Area",
    export: "Ekspor (Tujuan Luar Negeri)",
    import: "Impor (Masuk Indonesia)",
    quarantineActions: "Langkah Tindakan Karantina Spesifik",
    quarantineStatus: "Status Karantina",
    regulatoryStatus: "Status Regulasi",
    distributionMap: "Peta Sebaran OPTK",
    viewFullMap: "Lihat Peta Interaktif",
    interactiveMap: "Lihat Peta Interaktif",
    referencesTitle: "Referensi Ilmiah",
    scientificRefs: "Referensi Ilmiah",
    integratedSources: "Sumber Terintegrasi",
    treatmentGuide: "Panduan Perlakuan",
    mediaType: "Media Pembawa",
    method: "Metode",
    step: "Langkah",
    technicalParams: "Parameter Teknis",
    watchTutorial: "Tonton Video Demonstrasi",
    watchVideo: "Tonton Video Demonstrasi",
    prev: "Sebelumnya",
    next: "Selanjutnya",
    feedbackQuestion: "Apakah hasil ini akurat?",
    yes: "Ya",
    no: "Tidak",
    feedbackPlaceholder: "Ceritakan lebih lanjut (opsional)...",
    feedbackThanks: "Terima kasih atas masukan Anda!",
    submitFeedback: "Kirim Masukan",
    feedbackImprove: "Masukan Anda membantu kami meningkatkan akurasi sistem.",
    sendFeedback: "Kirim Masukan",
    send: "Kirim",
    statsTitle: "Statistik Sebaran OPTK (Kepkaban 571/2025)",
    statsSubtitle: "Visualisasi data resmi berdasarkan Keputusan Kepala Badan Karantina Indonesia Nomor 571 Tahun 2025",
    frequencyByStatus: "Komposisi OPTK Berdasarkan Status",
    frequencyByRegion: "Jumlah OPTK Berdasarkan Golongan",
    distributionByRegion: "Distribusi OPTK A2 Per Wilayah",
    trendOverTime: "Tren Identifikasi Aplikasi (Real-time)",
    totalIdentifications: "Total Jenis OPTK",
    region: "Wilayah",
    count: "Jumlah",
    date: "Tanggal",
    errorQuotaExceeded: "Kuota API telah habis. Silakan coba lagi nanti atau gunakan API key yang berbeda.",
    errorQuotaZero: "API Key yang Anda berikan adalah tipe Free Tier (Gratis). Google saat ini membatasi kuota untuk model ini. Silakan gunakan API Key berbayar atau coba lagi nanti.",
    errorUnavailable: "Model AI sedang mengalami permintaan tinggi (High Demand). Silakan coba lagi dalam beberapa menit.",
    errorTimeout: "Waktu habis (Timeout). Proses analisis AI memakan waktu lebih lama dari yang diperkirakan. Silakan coba lagi dengan gambar yang lebih jelas.",
    errorNetwork: "Gagal terhubung ke server. Ini bisa disebabkan oleh masalah jaringan atau server sedang dalam proses restart. Silakan tunggu beberapa saat dan coba lagi.",
    errorCookie: "Sesi koneksi terputus oleh sistem keamanan platform. Ini sering terjadi di lingkungan preview jika browser memblokir cookie pihak ketiga.",
    errorGeneric: "Terjadi kesalahan sistem yang tidak terduga saat menghubungi server.",
    loadingSteps: [
      'Mengunggah gambar sampel ke server...',
      'Menganalisis morfologi dan ciri fisik serangga...',
      'Mengekstrak data taksonomi dari gambar...',
      'Mengecek status OPTK di Kepkaban 571/2025...',
      'Mencari data sebaran geografis di EPPO Global Database...',
      'Mengkonsultasikan referensi teknis di CABI...',
      'Menghitung tingkat risiko dan dampak ekonomi...',
      'Menyusun rekomendasi tindakan karantina...',
      'Membuat laporan keputusan akhir...'
    ]
  },
  en: {
    headerTitle: "BARANTIN DSS",
    headerSubtitle: "Indonesian Quarantine Agency - Pest Detection",
    analysisFailed: "Analysis Failed",
    tryAgain: "Try Again",
    fixConnection: "Fix Connection",
    uploadSample: "Upload Sample",
    clickToChange: "Click to change image",
    dragDrop: "Select or Drag Image",
    formatInfo: "JPG, PNG Format (Max 5MB)",
    analyzeBtn: "Analyze with AI",
    analyzingBtn: "Analyzing...",
    integratedSystem: "Integrated System",
    analyzingTitle: "Analyzing",
    analyzingDesc: "AI is processing your image. This process is optimized to complete in less than 30 seconds.",
    processStatus: "Process Status",
    active: "Active",
    quarantineTips: "Quarantine Tips",
    quarantineTipText: "\"Ensure the sample image has sufficient lighting and focuses on distinctive insect body parts (wings, antennae, or legs) for more accurate identification results.\"",
    confidence: "Confidence",
    risk: "RISK",
    taxonomy: "Taxonomy",
    taxonomyHierarchy: "Taxonomy Hierarchy (Scientific Lineage)",
    kingdom: "Kingdom",
    phylum: "Phylum",
    class: "Class",
    order: "Order",
    family: "Family",
    genus: "Genus",
    species: "Species",
    target: "Target",
    riskAnalysis: "Risk Analysis",
    riskDetails: "Risk Details & Impact",
    potentialDamage: "Potential Damage",
    spreadRate: "Spread Rate",
    economicImpact: "Economic Impact",
    scientificReasoning: "Scientific Reasoning",
    scopusLiterature: "SCOPUS INDEXED LITERATURE",
    mitigationTitle: "Mitigation & Treatment Recommendations",
    mitigation: "Mitigation & Treatment Recommendations",
    farmerLevel: "Farmer Level",
    domesticMitigation: "Domestic / Inter-Area",
    domestic: "Domestic / Inter-Area",
    export: "Export (Overseas Destination)",
    import: "Import (Entering Indonesia)",
    quarantineActions: "Specific Quarantine Actions",
    quarantineStatus: "Quarantine Status",
    regulatoryStatus: "Regulatory Status",
    distributionMap: "Pest Distribution Map",
    viewFullMap: "View Interactive Map",
    interactiveMap: "View Interactive Map",
    referencesTitle: "Scientific References",
    scientificRefs: "Scientific References",
    integratedSources: "Integrated Sources",
    treatmentGuide: "Treatment Guide",
    mediaType: "Carrier Media",
    method: "Method",
    step: "Step",
    technicalParams: "Technical Parameters",
    watchTutorial: "Watch Demonstration Video",
    watchVideo: "Watch Demonstration Video",
    prev: "Previous",
    next: "Next",
    feedbackQuestion: "Is this result accurate?",
    yes: "Yes",
    no: "No",
    feedbackPlaceholder: "Tell us more (optional)...",
    feedbackThanks: "Thank you for your feedback!",
    submitFeedback: "Submit Feedback",
    feedbackImprove: "Your feedback helps us improve the system accuracy.",
    sendFeedback: "Send Feedback",
    send: "Send",
    statsTitle: "OPTK Distribution Statistics (Kepkaban 571/2025)",
    statsSubtitle: "Official data visualization based on the Decree of the Head of the Indonesian Quarantine Agency Number 571 of 2025",
    frequencyByStatus: "OPTK Composition by Status",
    frequencyByRegion: "Number of OPTK by Category",
    distributionByRegion: "OPTK A2 Distribution by Region",
    trendOverTime: "App Identification Trend (Real-time)",
    totalIdentifications: "Total Pest Types",
    region: "Region",
    count: "Count",
    date: "Date",
    errorQuotaExceeded: "API quota exceeded. Please try again later or use a different API key.",
    errorQuotaZero: "The API Key provided is a Free Tier key. Google currently restricts the quota for this model. Please use a paid API Key or try again later.",
    errorUnavailable: "The AI model is currently experiencing high demand. Please try again in a few minutes.",
    errorTimeout: "Timeout. The AI analysis process took longer than expected. Please try again with a clearer image.",
    errorNetwork: "Failed to connect to the server. This could be due to network issues or the server is restarting. Please wait a moment and try again.",
    errorCookie: "Connection session disconnected by platform security. This often happens in preview environments if the browser blocks third-party cookies.",
    errorGeneric: "An unexpected system error occurred while contacting the server.",
    loadingSteps: [
      'Uploading sample image to server...',
      'Analyzing morphology and physical characteristics...',
      'Extracting taxonomy data from image...',
      'Checking pest status in Kepkaban 571/2025...',
      'Searching geographical distribution in EPPO Global Database...',
      'Consulting technical references in CABI...',
      'Calculating risk level and economic impact...',
      'Drafting quarantine action recommendations...',
      'Generating final decision report...'
    ]
  }
};
